### ISSUE TITLE
Special characters get double encoded in truffleruby

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciimath#10]
When running on truffleruby, the `to_mathml` method double encodes special twice.

Consider the following input text:

```rb
(::AsciiMath.parse '+-x').to_mathml
```

This produces:

```xml
<math><mo>&amp;#xB1;</mo><mi>x</mi></math>
```

instead of the expected:

```xml
<math><mo>&#xB1;</mo><mi>x</mi></math>
```

It's possible this is a bug in truffleruby itself.

**Comment by eregon** [comment]
If TruffleRuby behaves differently than MRI, then it's most likely a bug in TruffleRuby.
Please report it to https://github.com/oracle/truffleruby/issues
A small reproducer is of course even better :smiley:

**Comment by mojavelinux** [comment]
@pepijnve Exactly what we needed to know. Thanks for filing the issue upstream!

@eregon While I discovered the issue in Asciidoctor, the stacktrace led to AsciiMath. So I filed the issue here to verify the source of the problem before we brought it to truffleruby. Thanks for the support!

**Comment by pepijnve** [comment]
@mojavelinux FYI, I dropped MRI 1.8 support as part of this change. Semver would require me to mark the gem as 2.0, but I'm not going to do that. 1.8 is sufficiently legacy that I hope this is a non issue for people...

**Comment by mojavelinux** [comment]
Fine by me. :+1:

**Comment by pepijnve** [comment]
@mojavelinux And the builds are green! 1.0.8 should be ready to go on rubygems.org.

**Comment by mojavelinux** [comment]
Thanks @pepijnve! The upstream builds are now green too.
