### ISSUE TITLE
AST Redesign

### ISSUE THREAD

**Issue by GarkGarcia** [asciidoctor/asciimath#19]
An issue for discussing the current AST redesign effort. The current proposal is the following:

1. Symbols should be identified by tokens (such as `:aleph`) instead of characters (such as `ℵ`). That way each builder can store an internal table that maps this tokens to their intended representation (like what I did with `LatexBuilde::CONSTANTS`).

2. "Operators" (`:operator`) and "identifiers" (`:identifier`) should no be distinguished. Their syntax is the same. I undertand that this distinction is pretty relevant for the MathML and HTML builders, but those could be dealt with by storing internal reference tables (an array or a set that stores all symbol identifiers that should be dealt with as operators).

3. "Operations" (`:unary`, `:binary`, `:trinary`) should be unified and expressed as `Hash`'s that store an array of operands. Each builder would then be responsible for segregating them appropriately. The order of the operands should be the same as the order in which they are expressed in asciimath.

4. Operations listed in [asciimath.org](https://asciimath.org/#syntax) (such as `hat` or `vec`) should no be expressed in terms of lower-level operations (such as`:over` or `:under`). Each builder would be responsible for converting the more specific representation to the more general one (the one done in terms of lower-level primitives) as necessary.

**Comment by pepijnve** [comment]
Almost done with v1 of this proposal. I'll push something out for review as soon as I have something working.

**Comment by pepijnve** [comment]
@GarkGarcia if you have a moment, could you have a look at https://github.com/asciidoctor/asciimath/tree/ast ?

I've made a tiny DSL to build the AST. This is used by both the parser itself and the first couple of unit tests I've written. The ASTs in parser_spec.rb should give you a good idea of what to expect as output from the parser. Is this kind of what you had in mind?

**Comment by GarkGarcia** [comment]
> @GarkGarcia if you have a moment, could you have a look at https://github.com/asciidoctor/asciimath/tree/ast ?
> 
> I've made a tiny DSL to build the AST. This is used by both the parser itself and the first couple of unit tests I've written. The ASTs in parser_spec.rb should give you a good idea of what to expect as output from the parser. Is this kind of what you had in mind?

Yes! That's pretty much what I have in mind! The DLS is great too. It's a shame we won't be able to match on the DSL expressions (since Ruby doesn't support generalized pattern matching).

It would be great if you could provide some documentation about which keyword corresponds to which symbols (in AsciiMath terms). Something like a translation table in AST.adoc would be fine.

**Comment by pepijnve** [comment]
I've added some extra AST details and the symbol table to https://github.com/asciidoctor/asciimath/blob/ast/AST.adoc

Does that cover everything you're looking for?

**Comment by GarkGarcia** [comment]
I believe so! Great work in there! I'll start adapting the LaTeX builder to the new AST tomorrow.

**Comment by GarkGarcia** [comment]
While adapting the `LatexBuilder` class to the new AST I've found a bug in the parser.

Apparently the expression `overbrace x` gets parsed as `["o", "v", "e", "r", "b", "r", "a", "c", "e", "x"]` instead of `{:type => :unary, :op => :overbrace, :e => "x"}`. The same goes for `underbrace x`.

**Comment by pepijnve** [comment]
> Apparently the expression overbrace x gets parsed as ["o", "v", "e", "r", "b", "r", "a", "c", "e", "x"]

`overbrace` is not in the symbol table and then that's the correct parsing. I'll go over the tables in asciimath.js again to see what else might be missing.

**Comment by GarkGarcia** [comment]
> > Apparently the expression overbrace x gets parsed as ["o", "v", "e", "r", "b", "r", "a", "c", "e", "x"]
> 
> `overbrace` is not in the symbol table and then that's the correct parsing. I'll go over the tables in asciimath.js again to see what else might be missing.

I think we're also missing `color` and `cancel`.

**Comment by pepijnve** [comment]
I'll add aliases for the symbols that are already there. For `color` and `cancel` I would open separate issues since those require extra changes to the output builders that are out of scope for the AST rework. I would prefer to this branch focused on just the AST so that I can land it on master as soon as possible.

**Comment by pepijnve** [comment]
All the TeX aliases have been added in 69ccea6e00a9f4f1bf9d5650c0a63b5615e46a81

**Comment by GarkGarcia** [comment]
> All the TeX aliases have been added in [69ccea6](https://github.com/asciidoctor/asciimath/commit/69ccea6e00a9f4f1bf9d5650c0a63b5615e46a81)

Great!

**Comment by GarkGarcia** [comment]
> I would prefer to keep this branch/issue focused on just the AST so that I can land it on master as soon as possible.

Sure, makes sense.

**Comment by pepijnve** [comment]
I've merged the ast branch and created #22 and #23 to track adding color and cancel support.
