### ISSUE TITLE
Add support for `color`

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciimath#22]

**Comment by pepijnve** [comment]
@GarkGarcia it seems like this one may also need extra packages to support in in LaTeX. Is that something you could look into?

**Comment by GarkGarcia** [comment]
> @GarkGarcia it seems like this one may also need extra packages to support in in LaTeX. Is that something you could look into?

Sure. The `\color` command from the `xcolor` package is necessary for this.

Luckily for us, it's included in all relevant LaTeX distributions. Just like the AMS packages, `xcolor` is pretty much standard. Also, it's supported by the Mathematical and Asciidoctor-LaTeX, so it shouldn't be a problem. I'll work on a fix.

**Comment by GarkGarcia** [comment]
Alright, LaTeX support for `color` is now integrated.
