### ISSUE TITLE
Avoid outputting `mfenced` tags

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciimath#26]
`mfenced` [will be deprecated](https://github.com/mathml-refresh/mathml/issues/2) in the next revision of MathML. Since `mfenced` is 100% equivalent to the expanded `<mrow><mo>left_fence</mo>content<mo>right_fence</mo></mrow>` form we should generate that instead.

**Comment by opoudjis** [comment]
... unless the 15 year old Microsoft Word stylesheet we are using to convert MathML into OOXML doesn't support it. Did the move away from mfenced make it into the testing we did of https://github.com/asciidoctor/asciimath/issues/14? From the date, it sounds like it did, and that we don't have a problem.

**Comment by pepijnve** [comment]
Thanks for refreshing my memory @opoudjis. How about toggling back to `mfenced` when the `:msword` option is used?

**Comment by pepijnve** [comment]
@opoudjis a906af4 restores mfenced output for ms office mode. Sorry for the regression.

**Comment by opoudjis** [comment]
Right; the output seemed ok when we tested it without mfenced, but let's keep it for now. I suspect that getting rid of mfenced actually fixed https://github.com/metanorma/metanorma-standoc/issues/228, and that mfenced might have been a crude mechanism to enforce `<mrow>` bracketing. But we should probably do proper testing of rendering with and without mfenced.
