### ISSUE TITLE
LaTeX subsup behaviour

### ISSUE THREAD

**Issue by GarkGarcia** [asciidoctor/asciimath#27]
A follow up to #25. As pointed by @davidfarmer, the LaTeX processor renders the expression `z_12^34` as `z_12^34` instead of `z_{12}^{34}`. This is an error.

I'm working on a patch to place curly braces around the arguments of `_` and `^`. However, to improve the readability of the output, the current algorithm does not place the curly braces around the following:

* Single characters or numbers. That meas `a_b` and `a_2` get rendered as `a_b` and `a_2` instead of `a_{b}` and `a_{2}` respectivelly. However, `a_(bc)` and `a_12` get rendered as `a_{b c}` and `a_{12}` repectivelly.

* Symbols. That means `a_(aleph)` gets rendered as `a_\aleph` instead of `a_{\aleph}`.

* Sections of text. That means `a_"some text"` gets rendered as `a_\text{some text}` instead of `a_{\text{some text}}`.

The same goes for `^`. Everything else is outputted inside curly braces. @davidfarmer Would this work for you?

**Comment by davidfarmer** [comment]
I agree that it is good to omit the curly brackets in those
single character and single sympol cases.

**Comment by GarkGarcia** [comment]
Alright, I'll submit the patch as soon as #24 is merged.

**Comment by GarkGarcia** [comment]
Fixed in https://github.com/asciidoctor/asciimath/commit/bbc91c5270c00e295f9f2984cfd9e8aa845d35f2.
