### ISSUE TITLE
Fix the spacing of some standard AsciiMath operators

### ISSUE THREAD

**Issue by GarkGarcia** [asciidoctor/asciimath#37]
Some standard AsciiMath operators - such as `Sin` - don't really have a direct LaTeX equivalent. As of now, the solution I came up with was to output `\text{Sin}`, which mean the ouput for `Sin x` and `"Sin" x` is the same.

The rendered output look like the following:

![CodeCogsEqn](https://user-images.githubusercontent.com/37553739/81349765-09f90e80-9097-11ea-9a54-1dd04bd36998.png)

One could then expect that `Sin x` (which is outputted as `\text{Sin} x`) would be rendered as:

![CodeCogsEqn(1)](https://user-images.githubusercontent.com/37553739/81349890-488ec900-9097-11ea-80cf-dc78a43c1118.png)

However, this is not the case. This is how `\text{Sin} x` is rendered in LaTeX:

![CodeCogsEqn(2)](https://user-images.githubusercontent.com/37553739/81350052-8f7cbe80-9097-11ea-8306-44304a983a05.png)

This could be fixed by outputting a `\;` between `\text{Sin}` and `x` (as of `\text{Sin} \; x`), but this is a bodge, a hack. This isn't a robust strategy. For example, if we were to adopt this strategy, the expression `Sin (x)`would be rendered as:

![CodeCogsEqn(3)](https://user-images.githubusercontent.com/37553739/81350608-ae2f8500-9098-11ea-8a9b-2d50a4b44947.png)

This is incorrect. The correct output would be:

![CodeCogsEqn(4)](https://user-images.githubusercontent.com/37553739/81350705-e5059b00-9098-11ea-9dc2-4da04022fe96.png)

It gets worse when dealing with infix operators - such as `and`, `or` and `if`. I'm not quite sure on how to deal with this. @davidfarmer @pepijnve I'd like your input.

Keep in mind I'm doing my best to make the LaTeX output as human-readable as possible. This could be easily fixed by using low-level TeX hacks, but as of now, my intention is to avoid them.

**Comment by davidfarmer** [comment]
I am not sure what you mean by "Sin".  Is that different than "sin",
which is what appears in the table on the asciimath home page?

If you wanted a function like the TeX `\sin` but with a capital S,
then you write it as `\operatorname{Sin}(x)`.

This Stackexchange question explains the point of operatorname
as distinct from text or mathrm:

https://tex.stackexchange.com/questions/48459/whats-the-difference-between-mathrm-and-operatorname

This one is also relevant:

https://tex.stackexchange.com/questions/19502/is-there-a-preference-of-when-to-use-text-and-mathrm

The main thing to understand is that mathrm ignores all white
space, just like everything in math mode.  But `\text` respects spaces
in its argument, like regular text in TeX.

**Comment by GarkGarcia** [comment]
> If you wanted a function like the TeX `\sin` but with a capital S, then you write it as `\operatorname{Sin}(x)`.

Yep, that's what I wanted.

> If you wanted a function like the TeX `\sin` but with a capital S, then you write it as `\operatorname{Sin}(x)`.

Thanks! That's just what I was looking for!

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/asciidoctor/asciimath/commit/74e5ba3355837774c202b4c61b085f9e0b62f612!
