### ISSUE TITLE
Transfer project to asciidoctor organization

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciimath#4]
This gem was written for the asciidoctor project. It would be preferable to transfer ownership of the repository to that organisation.

@mojavelinux are you ok with that?

**Comment by mojavelinux** [comment]
Indeed! Can you try to transfer? If you have difficulty, just let me know.

**Comment by pepijnve** [comment]
All done. Take good care of my baby 😉

**Comment by mojavelinux** [comment]
Whoohoo! It's in a safe space ;)
