### ISSUE TITLE
Releasing the recent changes to RubyGems

### ISSUE THREAD

**Issue by GarkGarcia** [asciidoctor/asciimath#45]
I think we're getting closer to the point of releasing the recent work we've done to RubyGems. That would _finally_ allow `asciidoctor-mathematical` and `asciidoctor-latex` to support AsciiMath.

@pepijnve Is there something you'd like to review before releasing the changes?

**Comment by pepijnve** [comment]
No I think we're good. Let me double check the CHANGELOG and then I'll cut a new release.

**Comment by pepijnve** [comment]
I've released the new version as `2.0.0` since we pretty much overhauled all the internals and the public interface has changed a bit.
