### ISSUE TITLE
Crash when italics symbol `ii` used independently

### ISSUE THREAD

**Issue by ronaldtse** [asciidoctor/asciimath#50]
In AsciiMath 1.x this asciimath expression worked:

```sh
E_{{ii}}
```

In 2.x this crashes:

```sh
asciimath 'E_{{ii}}'
```
= >
```
NoMethodError: undefined method `parent' for nil:NilClass
  .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/asciimath-2.0.1/lib/asciimath/ast.rb:109:in `add'
  .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/asciimath-2.0.1/lib/asciimath/ast.rb:228:in `initialize'
  .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/asciimath-2.0.1/lib/asciimath/ast.rb:35:in `new'
  .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/asciimath-2.0.1/lib/asciimath/ast.rb:35:in `unary'
  .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/asciimath-2.0.1/lib/asciimath/parser.rb:617:in `parse_simple_expression'
  .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/asciimath-2.0.1/lib/asciimath/parser.rb:546:in `parse_intermediate_expression'
```

It crashes because it considers `ii` the italics operator and instantiates it as one `Unary` object (`ii`), but it is actually a set of two `Identity` objects (`i` and `i`).

The workaround in 2.x is to add a space in between, i.e. `'E_{{i i}}'`:

```sh
asciimath 'E_{{i i}}'
```
=>
```xml
<math><msub><mi>E</mi><mrow><mo>{</mo><mrow><mi>i</mi><mi>i</mi></mrow><mo>}</mo></mrow></msub></math>
```

AsciiMath.org supports `E_{{ii}}` without problem.

This problem probably affects many `:symbol` entries that utilize only letters in `def self.add_default_parser_symbols(b)`.

**Comment by pepijnve** [comment]
I still have to figure out why this worked in 1.x. I did some digging through the git history already and it shouldn't have worked either.

`ii` is the italic unary operator, similar to `bb`. This is slightly different than asciimath.org which doesn't support italic. I tried `E_{{bb}}` as input in asciimath.org to see what happens there when operands are missing and that causes a parse error. b7e5c55 already fixes the parse error you bumped into by falling back to an identifier consisting of the empty string as operand.

**Comment by pepijnve** [comment]
@ronaldtse In 1.0.9, `E_{{ii}}` translated to `<math><msub><mi>E</mi><mstyle mathvariant=\"italic\"></mstyle></msub></math>`; not quite correct.

With b7e5c55 you get `<math><msub><mi>E</mi><mrow><mo>{</mo><mstyle mathvariant=\"italic\"><mi></mi></mstyle><mo>}</mo></mrow></msub></math>` instead. Is that acceptable?

**Comment by ronaldtse** [comment]
Thanks for following up on this! I guess the output of 1.0.9 wasn't proper either.

Perhaps the best way to move ahead is to:
1. have the output specified in b7e5c55
2. document that if an expression of identifiers that clash with any of the defined symbols (such as `ii`), a space should be placed in between for disambiguation.

What do you think?
