### ISSUE TITLE
phi/varphi option

### ISSUE THREAD

**Issue by opoudjis** [asciidoctor/asciimath#52]
There is a split in which character is used for phi and which for varphi. 

* Unicode has U+03C6 as phi and U+03D5 as the variant of phi
* TeX has them the other way around; so did Unicode before 1998
* Asciimath, MathJax, AsciiMathML all follow TeX as a default, and they all provide an option to give Unicode instead of TeX behaviour (fixphi = false, true by default): see e.g. https://github.com/asciimath/asciimathml/issues/14, https://github.com/mathjax/MathJax/issues/353, http://math.chapman.edu/~jipsen/asciimathjax/, http://asciimath.org
* I recommend that this gem follow suit, and have a fixphi option, true by default, which assigns phi and varphi the values the other way around by default

**Comment by pepijnve** [comment]
Makes sense to stick to what the other implementations do. I'll get that added ASAP.
