### ISSUE TITLE
Request normal font shift

### ISSUE THREAD

**Issue by opoudjis** [asciidoctor/asciimath#53]
We are using AsciiMath to enter expressions with units, https://github.com/metanorma/bipm-si-brochure/issues/54, and that requires the option of a font shift to normal, upright font. 

This is not present in most instances of Asciimath, but as I found in https://github.com/asciidoctor/asciimath/issues/7, https://runarberg.github.io/ascii2mathml/  (now offline) had `rm` (taken from TeX, although it properly refers to serifed font, not upright style). 

The option to force upright font is necessary, we feel, and we request rm as an addition to this gem's Asciimath:

asciimath/lib/asciimath/parser.rb : 

`b.add('sfbi', :normal, :unary)`

asciimath/lib/asciimath/latex.rb : 

`:normal => "\\mathrm",` (or: `\\mathup`)

asciimath/lib/asciimath/markup.rb : 

`b.add(:sans_serif_bold_italic, :normal, :font)`

**Comment by davidfarmer** [comment]
Instead of a shift in font, how about a way to indicate that
certain characters represent units?

That has the advantage of being semantic.  The work to implement
it is the same, but the mindset of the person writing the formula
is different.

**Comment by opoudjis** [comment]
We will be doing that in a month or so; but this is a genuine gap in Asciimath coverage anyway, and should be filled whatever we end up doing. if fonts shfits are allowed over non-text, they cannot ignore upright/normal font. If it is legal to say `ii(xyz)`, we should also be able to say `rm(xyz)`.

**Comment by pepijnve** [comment]
@opoudjis I think 685fd2f does what you're asking for. Regarding the original issue, wouldn't using text rather than an identifier, as the poster asked, have worked as well?

**Comment by pepijnve** [comment]
BTW, I did not change the semantics of `sfbi` as you suggest in your description. Was that a typo?

**Comment by opoudjis** [comment]
Yes, typo. 

We're trying to generate MathML compatible with the UnitsML proposed spec, which uses MathML `<mi mathvariant="normal">` for units. While mtext will work, mi is what we'd prefer to do, and of course either mtext or mi will require the normal font shift anyway. (And yes, in the longer term, we will look at a Units/Asciimath hybrid markup, but we're not there yet/)

And yes, your update is what we were after, thank you!

**Comment by opoudjis** [comment]
@pepijnve, would it be possible to release asciimath soon? We're about to give a document to an external party using this functionality.

**Comment by pepijnve** [comment]
Sorry Nick, I kind of forgot about this one. I'll make a new release right away.

**Comment by pepijnve** [comment]
Fix is in https://rubygems.org/gems/asciimath/versions/2.0.2
