### ISSUE TITLE
Support for MathML output for HTML backend?

### ISSUE THREAD

**Issue by SuperSonicHub1** [asciidoctor/asciimath#67]
After doing some reading, it seems that Asciidoctor does have support for STEM macro to MathML output, but it's only supported if you have the `asciimath` gem and are using the DocBook backend. I see no reason why MathML cannot be generated for use in the HTML backend if we standardize a variable like `stem-output`.

I want MathML/HTML support as people with [browsers that support MathML](https://developer.mozilla.org/en-US/docs/Web/MathML#browser_compatibility) shouldn't have to download multiple images (Asciidoctor Mathmatical) or execute JavaScript (MathJax).

P.S.: If this issue is in the wrong repository and should be in `asciidoctor` instead, feel free to move it.

**Comment by pepijnve** [comment]
The HTML backend is provided by the asciidoctor project itself indeed. This gem is only the asciimath parser and MathML generator.

I'm afraid I can't move your issue myself. Best to create a new one in the asciidoctor project and link to it from here.

**Comment by pepijnve** [comment]
Oh wait, just spotted the 'transfer issue' action in the bottom right corner. Let's give that a try.

**Comment by SuperSonicHub1** [comment]
Cool, I'll move it then.
