### ISSUE TITLE
Fix behaviour of ubrace, obrace with superscript, subscript

### ISSUE THREAD

**Issue by opoudjis** [asciidoctor/asciimath#69]
Issue raised in https://github.com/metanorma/metanorma/issues/235:

In Asciimath, `ubrace` followed by a subscript, and `obrace` followed by a superscript, is meant to render the subscript/superscript text under and over the expression, like with say `lim`. So:

`ubrace(((0.5, 0, 0.5),(0, 0.5, 0.5),(0, 0, 1)))_("Adjustment to texture space")`

should render as

<img width="270" alt="Στιγμιότυπο 2022-01-18, 22 57 20" src="https://user-images.githubusercontent.com/1911039/149933280-23a46533-2ddb-4372-9d73-4b2139ad5ae3.png">

as you can verify at http://asciimath.org

The current behaviour of the gem, which looks like the following, is incorrect:

![](https://user-images.githubusercontent.com/33627611/149669493-8e1374c1-5420-4a0a-89b5-f1d9f8fd0d17.PNG)

I've kludged some behaviour in PR #68 in markup.rb to enable that, adding `:underover => true` to `:underbrace` and `:overbrace`, and doing an ad hoc if branch to process it. I defer to you about how to do it properly.

**Comment by pepijnve** [comment]
@opoudjis do you happen to know how you would write this in latex? At the moment the same incorrect output is produced there so I would like to update that renderer as well.

**Comment by opoudjis** [comment]
... Update?

**Comment by pepijnve** [comment]
I don't have any mental space to work on this project at the moment I'm afraid. This is 100% volunteer work and I'm the only developer at the moment.

**Comment by opoudjis** [comment]
Well, I did the PR that addressed the MathML component; would you be ok if I added to the PR the LaTeX component?

**Comment by pepijnve** [comment]
If you have the time, yes that would be much appreciated. I haven't merged the PR yet because I would prefer to maintain feature parity across the backends.

**Comment by opoudjis** [comment]
Target is:

````
\underbrace {
\begin{pmatrix}
0 & 1\\ 
1 & 0
\end{pmatrix} }_{\text{Hello}}
````

**Comment by opoudjis** [comment]
Latex generated is:

`{\underbrace{\left ( \begin{matrix} 1 & 0 \\ 0 & 1 \end{matrix} \right )}}_{\text{Adjustment to texture space}}`

It needs to generate:

`\underbrace{\left ( \begin{matrix} 1 & 0 \\ 0 & 1 \end{matrix} \right )}_{\text{Adjustment to texture space}}`

**Comment by opoudjis** [comment]
@pepijnve I've added the needed LaTeX update. I've ended up hardcoding underbrace and overbrace processing, because you have a less rich symbol table by default for LaTeX processing than for MathML processing.

**Comment by opoudjis** [comment]
... Update? The PR should be good to go.

**Comment by pepijnve** [comment]
I finally got round to integrating your fix. Sorry for the delay.

**Comment by opoudjis** [comment]
No problem, thank you!
