### ISSUE TITLE
tilde(x) produces latex \~{x} instead of \tilde{x}

### ISSUE THREAD

**Issue by SeerLite** [asciidoctor/asciimath#75]
Hi!

When running `asciimath latex 'tilde(x)'` I expect the output to be `\tilde{x}`. This is what my latex compiler outputs as `x` with a tilde over it and is what is documented at https://asciimath.org

The current output is `\~{x}` instead, which produces a regular `x` for me. If it's possible to add some configuration to the latex preamble that converts it to `x` with a tilde over it then I'd appreciate that information. Otherwise, I'd like this asciimath converter to output `\tilde{x}` instead.

Thank you.

**Comment by pepijnve** [comment]
The latex lookup table explicitly contains `\~` as the output value at the moment. I'll change that to `\tilde`.

**Comment by pepijnve** [comment]
Should be fixed in v2.0.5

**Comment by SeerLite** [comment]
Thank you!
