### ISSUE TITLE
Escaped space not converted to no-break space

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciimath#8]
An escaped backslash should be converted to a no-break space. However, currently it's being left unprocessed.

Here's an example:

```
{ x \ : \ x in A ^^ x in B }
```

Expected output:

```
<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mo>{</mo><mi>x</mi><mo>&#xA0;</mo><mo>:</mo><mo>&#xA0;</mo><mi>x</mi><mo>&#x2208;</mo><mi>A</mi><mo>&#x2227;</mo><mi>x</mi><mo>&#x2208;</mo><mi>B</mi><mo>}</mo></mrow></math>
```

Actual output:

```
<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mo>{</mo><mi>x</mi><mi>\</mi><mi>:</mi><mi>\</mi><mi>x</mi><mo>&#x2208;</mo><mi>A</mi><mo>&#x2227;</mo><mi>x</mi><mo>&#x2208;</mo><mi>B</mi><mo>}</mo></mrow></math>
```

**Comment by pepijnve** [comment]
Looking into this one. It's not entirely clear how the js asciimath processor deals with escaping exactly. Looks like `\\` and `\ ` are handled, and for every other case a `\` is simply ignored.
I'll try to emulate that as well as possible.
