### ISSUE TITLE
Crash on truffleruby if input text contains spaces

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciimath#9]
The AsciiMath.parse method crashes on truffleruby if the input text contains spaces.

The following works:

```rb
AsciiMath.parse 'a>b'
```

The following does not work:

```rb
AsciiMath.parse 'a > b'
```

Instead, it fails with the following exception:

```
asciimath-1.0.7/lib/asciimath/parser.rb:473:in `parse_expression':
  undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by mojavelinux** [comment]
FYI, Travis CI now supports truffleruby. Just add an entry for truffleruby to the RVM matrix in the CI config.

**Comment by pepijnve** [comment]
@mojavelinux what are you using as development environment for truffleruby? Doesn't seem to be supported by RubyMine yet (at least not in the stable release).

**Comment by pepijnve** [comment]
vim's too spartan for me. Fine for simple changes, but for real development, debugging, etc. I prefer rich syntax highlighting, code navigation, an interactive debugger, etc...
I guess I'll have to switch back to `puts` debugging for this one for the time being (https://youtrack.jetbrains.com/issue/RUBY-23055).

**Comment by pepijnve** [comment]
@mojavelinux are you testing just 'native' truffleruby or also the JVM variant?

**Comment by eregon** [comment]
If TruffleRuby behaves differently than MRI, then it's most likely a bug in TruffleRuby.
Please report it to https://github.com/oracle/truffleruby/issues
A small reproducer is of course even better :smiley: 

BTW, missing TruffleRuby support in RubyMine is also something we would welcome a bug for. My understanding is it might already work but might require some configuration, which should be documented in TruffleRuby's docs.

**Comment by pepijnve** [comment]
@eregon done https://github.com/oracle/truffleruby/issues/1544

I was able to get truffle working with RubyMine by adding it manually. Doesn't get picked up from my rbenv installation though.

**Comment by eregon** [comment]
@pepijnve Thanks!

> I was able to get truffle working with RubyMine by adding it manually. Doesn't get picked up from my rbenv installation though.

Nice :smiley: 
There are also reports on the RubyMine tracker:
https://youtrack.jetbrains.com/issue/RUBY-23055
https://youtrack.jetbrains.com/issue/RUBY-19217
If you have a JetBrains account, could you vote them up?

**Comment by pepijnve** [comment]
The one upvote on 23055 was mine already :) Added a vote to 19217 as well.

**Comment by mojavelinux** [comment]
@pepijnve FYI truffleruby comes with a built-in debugger to which you can connect Chrome DevTools to start a debugging session. See https://www.graalvm.org/docs/reference-manual/languages/ruby/#provide-new-tooling
